#!/bin/sh
# Regenerates cloudflare-ips.conf from Cloudflare's published ranges, then reloads nginx after a syntax test.
set -eu
OUT="$(dirname "$0")/cloudflare-ips.conf"
V4=$(curl -fsS https://www.cloudflare.com/ips-v4); V6=$(curl -fsS https://www.cloudflare.com/ips-v6)
{
  echo "# Cloudflare edge address ranges, fetched $(date -u +%Y-%m-%d). Generated by update-cloudflare-ips.sh"
  for r in $V4 $V6; do echo "set_real_ip_from $r;"; done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo ""
  echo "geo \$realip_remote_addr \$from_cloudflare {"
  echo "    default 0;"
  for r in $V4 $V6; do echo "    $r 1;"; done
  echo "}"
} > "$OUT.new"
mv "$OUT.new" "$OUT"
echo "Wrote $OUT. Copy it to /etc/nginx/conf.d/ and run: nginx -t && systemctl reload nginx"
